/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package UIEmergentes;

import Controlador.InsertarProveedor;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/**
 *
 * @author yael
 */
public class AgregarProvedor extends javax.swing.JDialog {
 

    /**
     * Creates new form AgregarProvedor
     */
    public AgregarProvedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelRound1 = new UI.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        correo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        estadoU = new javax.swing.JComboBox<>();
        telefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnC2 = new UI.PanelRound();
        btnCan = new javax.swing.JButton();
        nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nCalle = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        calle = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        municipio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        pueblo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cPostal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnC3 = new UI.PanelRound();
        btnCan1 = new javax.swing.JButton();
        id_estado1 = new javax.swing.JComboBox<>();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(250, 176, 47));
        panelRound1.setRoundBottomLeft(45);
        panelRound1.setRoundBottomRight(45);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agrega un nuevo proveedor");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        jPanel1.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, -1));

        correo.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        correo.setForeground(new java.awt.Color(102, 102, 102));
        correo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        correo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        correo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                correoMouseClicked(evt);
            }
        });
        correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoActionPerformed(evt);
            }
        });
        jPanel1.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 211, 34));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setText("Nombre del proveedor");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, 21));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setText("Correo");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, 20));

        estadoU.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        estadoU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aguascalientes", "Baja California", "Baja California Sur", "Campeche", "Chiapas", "Chihuahua", "Ciudad de México", "Coahuila", "Colima", "Durango", "Estado de México", "Guanajuato", "Guerrero", "Hidalgo", "Jalisco", "Michoacán", "Morelos", "Nayarit", "Nuevo León", "Oaxaca", "Puebla", "Querétaro", "Quintana Roo", "San Luis Potosí", "Sinaloa", "Sonora", "Tabasco", "Tamaulipas", "Tlaxcala", "Veracruz", "Yucatán", "Zacatecas" }));
        estadoU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        estadoU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                estadoUMouseClicked(evt);
            }
        });
        estadoU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoUActionPerformed(evt);
            }
        });
        jPanel1.add(estadoU, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 211, 30));

        telefono.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        telefono.setForeground(new java.awt.Color(102, 102, 102));
        telefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        telefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        telefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                telefonoMouseClicked(evt);
            }
        });
        telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoActionPerformed(evt);
            }
        });
        jPanel1.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 211, 34));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setText("numero_telefono");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel8.setText("Estado del proveedor");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, 20));

        btnC2.setBackground(new java.awt.Color(250, 176, 47));
        btnC2.setRoundBottomLeft(40);
        btnC2.setRoundBottomRight(40);
        btnC2.setRoundTopLeft(40);
        btnC2.setRoundTopRight(40);
        btnC2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnC2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnC2MouseExited(evt);
            }
        });

        btnCan.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnCan.setText("ACEPTAR");
        btnCan.setBorder(null);
        btnCan.setContentAreaFilled(false);
        btnCan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCanMouseExited(evt);
            }
        });
        btnCan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnC2Layout = new javax.swing.GroupLayout(btnC2);
        btnC2.setLayout(btnC2Layout);
        btnC2Layout.setHorizontalGroup(
            btnC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnC2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnCan)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        btnC2Layout.setVerticalGroup(
            btnC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnC2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCan, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(btnC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, -1, -1));

        nombre.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        nombre.setForeground(new java.awt.Color(102, 102, 102));
        nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombreMouseClicked(evt);
            }
        });
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 211, 34));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setText("Calle");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, 21));

        nCalle.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        nCalle.setForeground(new java.awt.Color(102, 102, 102));
        nCalle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nCalle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        nCalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nCalleMouseClicked(evt);
            }
        });
        nCalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nCalleActionPerformed(evt);
            }
        });
        jPanel1.add(nCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 211, 34));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setText("No_Calle");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        calle.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        calle.setForeground(new java.awt.Color(102, 102, 102));
        calle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        calle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        calle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calleMouseClicked(evt);
            }
        });
        calle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calleActionPerformed(evt);
            }
        });
        jPanel1.add(calle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 211, 34));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel9.setText("Pueblo");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, 21));

        municipio.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        municipio.setForeground(new java.awt.Color(102, 102, 102));
        municipio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        municipio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        municipio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                municipioMouseClicked(evt);
            }
        });
        municipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                municipioActionPerformed(evt);
            }
        });
        jPanel1.add(municipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 211, 34));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setText("Municipio");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        pueblo.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        pueblo.setForeground(new java.awt.Color(102, 102, 102));
        pueblo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pueblo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pueblo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                puebloMouseClicked(evt);
            }
        });
        pueblo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puebloActionPerformed(evt);
            }
        });
        jPanel1.add(pueblo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 211, 34));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel11.setText("Estado");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, 21));

        cPostal.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        cPostal.setForeground(new java.awt.Color(102, 102, 102));
        cPostal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cPostal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        cPostal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cPostalMouseClicked(evt);
            }
        });
        cPostal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cPostalActionPerformed(evt);
            }
        });
        jPanel1.add(cPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 211, 34));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel12.setText("Codigo Postal");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, -1, -1));

        btnC3.setBackground(new java.awt.Color(153, 153, 153));
        btnC3.setRoundBottomLeft(40);
        btnC3.setRoundBottomRight(40);
        btnC3.setRoundTopLeft(40);
        btnC3.setRoundTopRight(40);
        btnC3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnC3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnC3MouseExited(evt);
            }
        });

        btnCan1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnCan1.setText("CANCELAR");
        btnCan1.setBorder(null);
        btnCan1.setContentAreaFilled(false);
        btnCan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCan1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCan1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCan1MouseExited(evt);
            }
        });
        btnCan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCan1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnC3Layout = new javax.swing.GroupLayout(btnC3);
        btnC3.setLayout(btnC3Layout);
        btnC3Layout.setHorizontalGroup(
            btnC3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnC3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCan1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnC3Layout.setVerticalGroup(
            btnC3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnC3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCan1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(btnC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, -1, -1));

        id_estado1.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        id_estado1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        id_estado1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        id_estado1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                id_estado1MouseClicked(evt);
            }
        });
        id_estado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_estado1ActionPerformed(evt);
            }
        });
        jPanel1.add(id_estado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 211, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void estadoUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoUActionPerformed

    private void telefonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telefonoMouseClicked
        telefono.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoMouseClicked

    private void telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoActionPerformed

    private void btnCanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCanMouseEntered
        //[250,176,47]
    }//GEN-LAST:event_btnCanMouseEntered

    private void btnCanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCanMouseExited

    }//GEN-LAST:event_btnCanMouseExited

    private void btnCanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanActionPerformed
// Obtener valores de los componentes de la interfaz
    String nombreProveedor = nombre.getText();
    String telefono1 = telefono.getText();
    String correo1 = correo.getText();
    String estadoProveedor = (String) id_estado1.getSelectedItem();
    String calle1 = calle.getText();
    String numero = nCalle.getText();
    String pueblo1 = pueblo.getText();
    String municipio1 = municipio.getText();
    String estadoUbicacion = (String) estadoU.getSelectedItem();
    String codigoPostal = cPostal.getText();

    // Validar campos vacíos
    if (nombreProveedor.isEmpty() || telefono1.isEmpty() || correo1.isEmpty() ||
        estadoProveedor == null || estadoProveedor.isEmpty() ||
        calle1.isEmpty() || numero.isEmpty() || pueblo1.isEmpty() ||
        municipio1.isEmpty() || estadoUbicacion.isEmpty() || codigoPostal.isEmpty()) {

        JOptionPane.showMessageDialog(this, "Por favor, rellena todos los campos.",
            "Campos incompletos", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Crear instancia del DAO
    InsertarProveedor dao = new InsertarProveedor();
    
    try {
        // Llamar al método para insertar el proveedor
        boolean exito = dao.insertarProveedorCompleto(
                nombreProveedor,
                telefono1,
                correo1,
                estadoProveedor,
                calle1,
                numero,
                pueblo1,
                municipio1,
                estadoUbicacion,
                codigoPostal);
        
        if (exito) {
            JOptionPane.showMessageDialog(this, "Proveedor agregado exitosamente", 
                "Éxito", JOptionPane.INFORMATION_MESSAGE);
            limpiarCamposProveedor();
        } else {
            JOptionPane.showMessageDialog(this, "Error al agregar el proveedor", 
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, 
            "Error de base de datos: " + ex.getMessage(), 
            "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
    this.dispose();
    }//GEN-LAST:event_btnCanActionPerformed
private void limpiarCamposProveedor() {
    nombre.setText("");
    telefono.setText("");
    correo.setText("");
    calle.setText("");
    nCalle.setText("");
    pueblo.setText("");
    municipio.setText("");
    cPostal.setText("");
    id_estado1.setSelectedIndex(0);
    estadoU.setSelectedIndex(0);
}
    private void btnC2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnC2MouseEntered

    }//GEN-LAST:event_btnC2MouseEntered

    private void btnC2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnC2MouseExited

    }//GEN-LAST:event_btnC2MouseExited

    private void nombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreMouseClicked
nombre.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_nombreMouseClicked

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoActionPerformed

    private void correoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_correoMouseClicked
        correo.setText("");  // TODO add your handling code here:
    }//GEN-LAST:event_correoMouseClicked

    private void nCalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nCalleMouseClicked
nCalle.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_nCalleMouseClicked

    private void nCalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nCalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nCalleActionPerformed

    private void calleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calleMouseClicked
calle.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_calleMouseClicked

    private void calleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calleActionPerformed

    private void municipioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_municipioMouseClicked
municipio.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_municipioMouseClicked

    private void municipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_municipioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_municipioActionPerformed

    private void puebloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_puebloMouseClicked
pueblo.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_puebloMouseClicked

    private void puebloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puebloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puebloActionPerformed

    private void cPostalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cPostalMouseClicked
cPostal.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_cPostalMouseClicked

    private void cPostalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cPostalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cPostalActionPerformed

    private void btnCan1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCan1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCan1MouseEntered

    private void btnCan1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCan1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCan1MouseExited

    private void btnCan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCan1ActionPerformed
this.dispose();
    }//GEN-LAST:event_btnCan1ActionPerformed

    private void btnC3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnC3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnC3MouseEntered

    private void btnC3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnC3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnC3MouseExited

    private void btnCan1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCan1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCan1MouseClicked

    private void estadoUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estadoUMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoUMouseClicked

    private void id_estado1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_id_estado1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_id_estado1MouseClicked

    private void id_estado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_estado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_estado1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AgregarProvedor dialog = new AgregarProvedor(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private UI.PanelRound btnC2;
    private UI.PanelRound btnC3;
    private javax.swing.JButton btnCan;
    private javax.swing.JButton btnCan1;
    private javax.swing.JTextField cPostal;
    private javax.swing.JTextField calle;
    private javax.swing.JTextField correo;
    private javax.swing.JComboBox<String> estadoU;
    private javax.swing.JComboBox<String> id_estado1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField municipio;
    private javax.swing.JTextField nCalle;
    private javax.swing.JTextField nombre;
    private UI.PanelRound panelRound1;
    private javax.swing.JTextField pueblo;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
