/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UIEmergentes;

import java.sql.SQLException;
import ManejoTablas.InsertarProducto;
import MetodoAdicionales.CreadorBarras;
import Modelo.MostrarProveedor;
import UI.Inventario;
import UI.inicio;
import com.google.zxing.BarcodeFormat;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import javax.imageio.ImageIO;
import javax.print.Doc;
import javax.print.DocFlavor;
import javax.print.DocPrintJob;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.print.SimpleDoc;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author salin
 */
public class AgregarInventario extends javax.swing.JDialog {

    /**
     * Creates new form AgregarInventario
     */
    public AgregarInventario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/logo6.png")).getImage());
        imagen.setEditable(false);
codigo.setEditable(false);
pVenta.setEditable(false);
id_provedor.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelRound1 = new UI.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        id_provedor = new javax.swing.JTextField();
        imagen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        id_tipo = new javax.swing.JComboBox<>();
        descripcion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        barra = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pGanancia = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        id_medida = new javax.swing.JComboBox<>();
        cantidad = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        fechaIngreso1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btnC2 = new UI.PanelRound();
        btnCan = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        pCompra = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        pVenta = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        mTotal = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnC3 = new UI.PanelRound();
        btnCan1 = new javax.swing.JButton();
        stockminimo = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(250, 176, 47));
        panelRound1.setRoundBottomLeft(45);
        panelRound1.setRoundBottomRight(45);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agrega un nuevo producto");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        jPanel1.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, -1));

        id_provedor.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        id_provedor.setForeground(new java.awt.Color(102, 102, 102));
        id_provedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        id_provedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        id_provedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                id_provedorMouseClicked(evt);
            }
        });
        id_provedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_provedorActionPerformed(evt);
            }
        });
        jPanel1.add(id_provedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 211, 34));

        imagen.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        imagen.setForeground(new java.awt.Color(102, 102, 102));
        imagen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        imagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        imagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagenActionPerformed(evt);
            }
        });
        jPanel1.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 211, 34));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setText("Nombre del producto");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, 21));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setText("Selecciona un provedor");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, 20));

        id_tipo.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        id_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Construccion", "Ferreteria" }));
        id_tipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        id_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_tipoActionPerformed(evt);
            }
        });
        jPanel1.add(id_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 211, 30));

        descripcion.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        descripcion.setForeground(new java.awt.Color(102, 102, 102));
        descripcion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        descripcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        descripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                descripcionMouseClicked(evt);
            }
        });
        descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descripcionActionPerformed(evt);
            }
        });
        jPanel1.add(descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 211, 34));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setText("Descripcion del producto");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel8.setText("Tipo de producto");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, 20));

        codigo.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        codigo.setForeground(new java.awt.Color(102, 102, 102));
        codigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        codigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoActionPerformed(evt);
            }
        });
        jPanel1.add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 211, 34));

        barra.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jPanel1.add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 210, 80));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel11.setText("Porcentaje de ganancia");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, -1, 20));

        pGanancia.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        pGanancia.setForeground(new java.awt.Color(102, 102, 102));
        pGanancia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pGanancia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pGanancia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pGananciaMouseClicked(evt);
            }
        });
        pGanancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pGananciaActionPerformed(evt);
            }
        });
        jPanel1.add(pGanancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 211, 34));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel12.setText("Unidad de medida");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, -1, 20));

        id_medida.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        id_medida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pieza", "litro", "kilogramo", "metro", "paquete", "Tonelada ", "Gramo", "Mililitro", " " }));
        id_medida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        id_medida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_medidaActionPerformed(evt);
            }
        });
        jPanel1.add(id_medida, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 560, 211, 30));

        cantidad.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        cantidad.setForeground(new java.awt.Color(102, 102, 102));
        cantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cantidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        cantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cantidadMouseClicked(evt);
            }
        });
        cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadActionPerformed(evt);
            }
        });
        jPanel1.add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 630, 211, 34));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel13.setText("Cantidad comprada");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 610, -1, 20));

        fechaIngreso1.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        fechaIngreso1.setForeground(new java.awt.Color(102, 102, 102));
        fechaIngreso1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fechaIngreso1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        fechaIngreso1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fechaIngreso1MouseClicked(evt);
            }
        });
        fechaIngreso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaIngreso1ActionPerformed(evt);
            }
        });
        jPanel1.add(fechaIngreso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 560, 211, 34));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel15.setText("Fecha de ingreso");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, -1, 20));

        btnC2.setBackground(new java.awt.Color(250, 176, 47));
        btnC2.setRoundBottomLeft(40);
        btnC2.setRoundBottomRight(40);
        btnC2.setRoundTopLeft(40);
        btnC2.setRoundTopRight(40);
        btnC2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnC2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnC2MouseExited(evt);
            }
        });

        btnCan.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnCan.setText("ACEPTAR");
        btnCan.setBorder(null);
        btnCan.setContentAreaFilled(false);
        btnCan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCanMouseExited(evt);
            }
        });
        btnCan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnC2Layout = new javax.swing.GroupLayout(btnC2);
        btnC2.setLayout(btnC2Layout);
        btnC2Layout.setHorizontalGroup(
            btnC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnC2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnCan)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        btnC2Layout.setVerticalGroup(
            btnC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnC2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCan, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(btnC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 740, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Calcular precio de venta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 440, -1));

        jButton2.setBackground(new java.awt.Color(0, 102, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Cargar o añade");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 210, -1));

        jButton3.setBackground(new java.awt.Color(0, 102, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Generar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 210, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setText("Precio de compra unitario");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, 20));

        pCompra.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        pCompra.setForeground(new java.awt.Color(102, 102, 102));
        pCompra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pCompra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pCompraMouseClicked(evt);
            }
        });
        pCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pCompraActionPerformed(evt);
            }
        });
        jPanel1.add(pCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 211, 34));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel16.setText("Generacion de precio de venta");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, -1, 20));

        pVenta.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        pVenta.setForeground(new java.awt.Color(102, 102, 102));
        pVenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pVenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pVentaActionPerformed(evt);
            }
        });
        jPanel1.add(pVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 211, 34));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel14.setText("Carga una imagen ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        nombre.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        nombre.setForeground(new java.awt.Color(102, 102, 102));
        nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombreMouseClicked(evt);
            }
        });
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 211, 34));

        jButton4.setBackground(new java.awt.Color(0, 102, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setText("Cargar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 210, -1));

        mTotal.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        mTotal.setForeground(new java.awt.Color(102, 102, 102));
        mTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        mTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mTotalMouseClicked(evt);
            }
        });
        mTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mTotalActionPerformed(evt);
            }
        });
        jPanel1.add(mTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 640, 211, 34));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel17.setText("Monto Total");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 620, -1, 20));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel18.setText("Genera un codigo:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        btnC3.setBackground(new java.awt.Color(153, 153, 153));
        btnC3.setRoundBottomLeft(40);
        btnC3.setRoundBottomRight(40);
        btnC3.setRoundTopLeft(40);
        btnC3.setRoundTopRight(40);
        btnC3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnC3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnC3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnC3MouseExited(evt);
            }
        });

        btnCan1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnCan1.setText("CANCELAR");
        btnCan1.setBorder(null);
        btnCan1.setContentAreaFilled(false);
        btnCan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCan1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCan1MouseExited(evt);
            }
        });
        btnCan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCan1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnC3Layout = new javax.swing.GroupLayout(btnC3);
        btnC3.setLayout(btnC3Layout);
        btnC3Layout.setHorizontalGroup(
            btnC3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnC3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnCan1)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        btnC3Layout.setVerticalGroup(
            btnC3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnC3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCan1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(btnC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 740, -1, -1));

        stockminimo.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        stockminimo.setForeground(new java.awt.Color(102, 102, 102));
        stockminimo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        stockminimo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        stockminimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stockminimoMouseClicked(evt);
            }
        });
        stockminimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockminimoActionPerformed(evt);
            }
        });
        jPanel1.add(stockminimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 700, 211, 34));

        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel19.setText("Stock Minimo");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 680, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void id_provedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_provedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_provedorActionPerformed

    private void imagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagenActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_imagenActionPerformed

    private void descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descripcionActionPerformed

    private void codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoActionPerformed

    private void pGananciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pGananciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pGananciaActionPerformed

    private void cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadActionPerformed

    private void fechaIngreso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaIngreso1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaIngreso1ActionPerformed

    private void btnCanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCanMouseEntered
 //[250,176,47]
    }//GEN-LAST:event_btnCanMouseEntered

    private void btnCanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCanMouseExited

    }//GEN-LAST:event_btnCanMouseExited

    private void btnCanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanActionPerformed
    // Obtener valores de los componentes de la interfaz
    String nombreProducto = nombre.getText().trim();
    String descripcionProducto = descripcion.getText().trim();
    String tipoProducto = (String) id_tipo.getSelectedItem();
    String codigoProducto = codigo.getText().trim();
    String precioCompraStr = pCompra.getText().trim();
    String precioVentaStr = pVenta.getText().trim();
    String cantidadProductoStr = cantidad.getText().trim();
    String unidadMedida = (String) id_medida.getSelectedItem();
    String fechaIngresoStr = fechaIngreso1.getText().trim();
    String nombreProveedor = id_provedor.getText().trim();
    String imagenProducto = imagen.getText().trim();
    String stockMinStr = stockminimo.getText().trim(); // Nuevo campo para stock mínimo

    // Validar campos vacíos (hacer el proveedor e imagen opcionales)
    if (nombreProducto.isEmpty() || descripcionProducto.isEmpty() || tipoProducto == null || tipoProducto.isEmpty() ||
        codigoProducto.isEmpty() || precioCompraStr.isEmpty() || precioVentaStr.isEmpty() ||
        cantidadProductoStr.isEmpty() || unidadMedida == null || unidadMedida.isEmpty() ||
        fechaIngresoStr.isEmpty() || stockMinStr.isEmpty()) { // Añadida validación para stock mínimo

        JOptionPane.showMessageDialog(this, "Por favor, rellena todos los campos obligatorios.",
            "Campos incompletos", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Validar que el código de barras solo contenga dígitos
    if (!codigoProducto.matches("\\d+")) {
        JOptionPane.showMessageDialog(this, "El código de barras debe contener solo números.",
            "Código inválido", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Crear instancia del DAO dentro del método
    InsertarProducto dao = new InsertarProducto();

    try {
        // Convertir los datos numéricos y validar sus rangos
        float precioCompra = Float.parseFloat(precioCompraStr);
        float precioVenta = Float.parseFloat(precioVentaStr);
        int cantidadProducto = Integer.parseInt(cantidadProductoStr);
        int stockMinimo = Integer.parseInt(stockMinStr); // Convertir stock mínimo a entero

        if (precioCompra <= 0) {
            JOptionPane.showMessageDialog(this, "El precio de compra debe ser mayor que 0.",
                "Precio inválido", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (precioVenta <= 0) {
            JOptionPane.showMessageDialog(this, "El precio de venta debe ser mayor que 0.",
                "Precio inválido", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (cantidadProducto < 0) {
            JOptionPane.showMessageDialog(this, "La cantidad no puede ser negativa.",
                "Cantidad inválida", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (stockMinimo < 0) {
            JOptionPane.showMessageDialog(this, "El stock mínimo no puede ser negativo.",
                "Stock inválido", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validar formato de fecha
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        sdf.setLenient(false); // Para evitar fechas como 2025-02-30
        Date fechaIngreso = sdf.parse(fechaIngresoStr);

        // Validar código de barras único
        if (dao.codigoBarrasExiste(codigoProducto)) {
            JOptionPane.showMessageDialog(this, "El código de barras ya existe.",
                "Código duplicado", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Llamar al método para insertar el producto (nombreProveedor e imagen opcionales)
        boolean exito = dao.insertarProductoCompleto(
            nombreProducto,
            descripcionProducto,
            tipoProducto,
            codigoProducto,
            precioCompra,
            precioVenta,
            cantidadProducto,
            unidadMedida,
            fechaIngreso,
            nombreProveedor.isEmpty() ? null : nombreProveedor,
            imagenProducto.isEmpty() ? null : imagenProducto,
            stockMinimo // Añadido el parámetro de stock mínimo
        );

        if (exito) {
            JOptionPane.showMessageDialog(this, "Producto agregado exitosamente.",
                "Éxito", JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Error al agregar el producto.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, 
            "Error de base de datos: " + ex.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this,
            "Formato numérico incorrecto: " + ex.getMessage(),
            "Error de formato", JOptionPane.ERROR_MESSAGE);
    } catch (ParseException ex) {
        JOptionPane.showMessageDialog(this,
            "Formato de fecha incorrecto. Usa yyyy-MM-dd.",
            "Fecha inválida", JOptionPane.ERROR_MESSAGE);
    }
    
    this.dispose();
    }//GEN-LAST:event_btnCanActionPerformed
private void limpiarCampos() {
    nombre.setText("");
    descripcion.setText("");
    codigo.setText("");
    pCompra.setText("");
    pVenta.setText("");
    cantidad.setText("");
    id_provedor.setText("");
    imagen.setText("");
    fechaIngreso1.setText("");
    stockminimo.setText(""); // Limpiar el campo de stock mínimo
    id_tipo.setSelectedIndex(0);
    id_medida.setSelectedIndex(0);
}
    private void btnC2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnC2MouseEntered
       
    }//GEN-LAST:event_btnC2MouseEntered

    private void btnC2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnC2MouseExited
     
    }//GEN-LAST:event_btnC2MouseExited

    private void id_provedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_id_provedorMouseClicked
      id_provedor.setText("");  // TODO add your handling code here:
    }//GEN-LAST:event_id_provedorMouseClicked

    private void descripcionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descripcionMouseClicked
descripcion.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_descripcionMouseClicked

    private void id_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_tipoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
double precioCompra = Double.parseDouble(pCompra.getText());
double porcentajeGanancia = Double.parseDouble(pGanancia.getText());

double gananciaCi = precioCompra / (1 -(porcentajeGanancia/100)); 

pVenta.setText(String.format("%.2f", gananciaCi)); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// Crear solo UNA instancia del diálogo
    SeleccionaProvedor dialog = new SeleccionaProvedor((java.awt.Frame) this.getParent(), true);
    dialog.setLocationRelativeTo(this);
    dialog.setVisible(true); 
    
    // Obtener el proveedor seleccionado
    MostrarProveedor proveedor = dialog.getProveedorSeleccionado();
    if (proveedor != null) {
        actualizarCamposProveedor(proveedor);
    }
    }//GEN-LAST:event_jButton2ActionPerformed
private MostrarProveedor proveedorActual;
    private void actualizarCamposProveedor(MostrarProveedor proveedor) {
    id_provedor.setText(proveedor.getNombre());
    
    // Guardar referencia si es necesario
    this.proveedorActual = proveedor;
}
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
CreadorBarras cb= new CreadorBarras(); 
        String codigoBarras = cb.generarCodigoBarras();
    codigo.setText(codigoBarras);

    try {
        BufferedImage imagenCodigo = cb.generarImagenCodigoBarras(codigoBarras);
        
        // Mostrar en JLabel
        ImageIcon icono = new ImageIcon(imagenCodigo);
        barra.setIcon(icono);  // Asegúrate de tener un JLabel con nombre 'barra'

        // Guardar como PDF
        String nombreArchivo = "codigo_" + codigoBarras + ".pdf";
        cb.guardarImagenComoPDF(imagenCodigo, nombreArchivo);

        JOptionPane.showMessageDialog(this, "Código guardado en PDF: " + nombreArchivo);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton3ActionPerformed


    private void pCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pCompraMouseClicked
   pCompra.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_pCompraMouseClicked

    private void pCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pCompraActionPerformed

    private void pVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pVentaActionPerformed

    private void pGananciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pGananciaMouseClicked
pGanancia.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_pGananciaMouseClicked

    private void fechaIngreso1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechaIngreso1MouseClicked
fechaIngreso1.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_fechaIngreso1MouseClicked

    private void cantidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cantidadMouseClicked
   cantidad.setText("");     // TODO add your handling code here:
    }//GEN-LAST:event_cantidadMouseClicked

    private void nombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreMouseClicked
nombre.setText("");          // TODO add your handling code here:
    }//GEN-LAST:event_nombreMouseClicked

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Selecciona una imagen");

    int result = fileChooser.showOpenDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
        File selectedFile = fileChooser.getSelectedFile();
        String fileName = selectedFile.getName();

        // Ruta del paquete imagenesProductos dentro del proyecto
        File destino = new File("src/imagenesProductos/" + fileName);

        try {
            // Copia la imagen al paquete imagenesProductos
            Files.copy(selectedFile.toPath(), destino.toPath(), StandardCopyOption.REPLACE_EXISTING);

            // Muestra la ruta relativa en el campo de texto
            imagen.setText("/imagenesProductos/" + fileName);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al copiar la imagen: " + ex.getMessage());
        }
    }
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void mTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mTotalMouseClicked
mTotal.setText("");         // TODO add your handling code here:
    }//GEN-LAST:event_mTotalMouseClicked

    private void mTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mTotalActionPerformed

    private void btnCan1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCan1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCan1MouseEntered

    private void btnCan1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCan1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCan1MouseExited

    private void btnCan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCan1ActionPerformed
 this.dispose();
    }//GEN-LAST:event_btnCan1ActionPerformed

    private void btnC3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnC3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnC3MouseEntered

    private void btnC3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnC3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnC3MouseExited

    private void btnC3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnC3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnC3MouseClicked

    private void id_medidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_medidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_medidaActionPerformed

    private void stockminimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockminimoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_stockminimoMouseClicked

    private void stockminimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockminimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockminimoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AgregarInventario dialog = new AgregarInventario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barra;
    private UI.PanelRound btnC2;
    private UI.PanelRound btnC3;
    private javax.swing.JButton btnCan;
    private javax.swing.JButton btnCan1;
    private javax.swing.JTextField cantidad;
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField descripcion;
    private javax.swing.JTextField fechaIngreso1;
    private javax.swing.JComboBox<String> id_medida;
    private javax.swing.JTextField id_provedor;
    private javax.swing.JComboBox<String> id_tipo;
    private javax.swing.JTextField imagen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mTotal;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField pCompra;
    private javax.swing.JTextField pGanancia;
    private javax.swing.JTextField pVenta;
    private UI.PanelRound panelRound1;
    private javax.swing.JTextField stockminimo;
    // End of variables declaration//GEN-END:variables
}
