/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UIEmergentes;

import Modelo.*;
import ManejoTablas.*;
import java.awt.Color;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author salin
 */
public class AgregarClientePV extends javax.swing.JDialog {
    private boolean e1 = false,e2 = false,e3 = false,e4 = false,e5 = false,e6 = false,e7 = false,e8 = false, aceptado, mor, fis=true;
    private ManejoDirecciones manejomunicipios = new ManejoDirecciones();
    private ManejoClientes manejoclientes = new ManejoClientes();
    private int idCliente;
    private PagarVenta pagarventa = new PagarVenta();
    /**
     * Creates new form AgregarInventario
     */
    public AgregarClientePV(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/logo6.png")).getImage());
        cargarDatosComboBox();
        btnC2.setEnabled(false);
        btnAceptar.setEnabled(false);
        
        DocumentListener validadorRFC = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                validarYActualizarBoton();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                validarYActualizarBoton();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                validarYActualizarBoton();
            }
        };

        // Asignar el listener a cada campo relevante
        txtNombre.getDocument().addDocumentListener(validadorRFC);
        txtAPaterno.getDocument().addDocumentListener(validadorRFC);
        txtAMaterno.getDocument().addDocumentListener(validadorRFC);
        txtFecNac.getDocument().addDocumentListener(validadorRFC);
        txtRfc.getDocument().addDocumentListener(validadorRFC);
        
        cboPersona.addActionListener(e -> {
    String seleccion = (String) cboPersona.getSelectedItem();

    switch (seleccion) {
        case "Fisica":
            lblNombre.setText("Nombre del Cliente:");
            lblFecha.setText("Fecha de Nacimiento:");
            lblAPaterno.setVisible(true);
            lblAMaterno.setVisible(true);
            txtAPaterno.setVisible(true);
            txtAMaterno.setVisible(true);
            break;
        case "Moral":
            lblNombre.setText("Nombre de la empresa:");
            lblFecha.setText("Fecha de Creación");
            lblAPaterno.setVisible(false);
            lblAMaterno.setVisible(false);
            txtAPaterno.setVisible(false);
            txtAMaterno.setVisible(false);
            break;
        default:
            break;
    }
});
    }
    
    private void cargarDatosComboBox(){
        try {
            List<Municipio> listaMunicipios = manejomunicipios.obtenerMunicipiosPorEstado(1);
            cboMunicipios.removeAllItems();
            for(Municipio mun : listaMunicipios){
                cboMunicipios.addItem(mun);
            }
            cboMunicipios.addActionListener(e -> actualizarPueblos());
            if(cboMunicipios.getItemCount() > 0){
                actualizarPueblos();
            }

        } catch (SQLException ex) { }
    }

    
    private void actualizarPueblos(){
    try {
        Municipio municipioSeleccionado = (Municipio)cboMunicipios.getSelectedItem();
        if(municipioSeleccionado != null){
                List<Pueblo> listaPueblos = manejomunicipios.obtenerPueblosPorMunicipio(municipioSeleccionado.getIdMunicipio());
                cboPueblos.removeAllItems();
                for(Pueblo pue : listaPueblos){
                cboPueblos.addItem(pue);
                }  
            }   
        } catch (SQLException ex) {}
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelRound1 = new UI.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtNumeroTel = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblAMaterno = new javax.swing.JLabel();
        cboMunicipios = new javax.swing.JComboBox<>();
        txtAPaterno = new javax.swing.JTextField();
        lblAPaterno = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCalle = new javax.swing.JTextField();
        btnC2 = new UI.PanelRound();
        btnAceptar = new javax.swing.JButton();
        txtAMaterno = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtNumeroCasa = new javax.swing.JTextField();
        btnC3 = new UI.PanelRound();
        btnCancelar = new javax.swing.JButton();
        cboPueblos = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtRfc = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        txtFecNac = new javax.swing.JTextField();
        lblValidar = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cboPersona = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        panelRound1.setBackground(new java.awt.Color(250, 176, 47));
        panelRound1.setRoundBottomLeft(45);
        panelRound1.setRoundBottomRight(45);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agrega nuevo Cliente");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        txtNombre.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(153, 153, 153));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre.setText("Ingresa un nombre");
        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMouseClicked(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtNumeroTel.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        txtNumeroTel.setForeground(new java.awt.Color(153, 153, 153));
        txtNumeroTel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumeroTel.setText("Ingresa un numero Telefonico");
        txtNumeroTel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtNumeroTel.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtNumeroTel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNumeroTelMouseClicked(evt);
            }
        });
        txtNumeroTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroTelActionPerformed(evt);
            }
        });
        txtNumeroTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroTelKeyTyped(evt);
            }
        });

        lblNombre.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("Nombre del Cliente :");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Numero Telefonico :");

        lblAMaterno.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblAMaterno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAMaterno.setText("Apellido Materno :");

        cboMunicipios.setBackground(new java.awt.Color(250, 176, 47));
        cboMunicipios.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        cboMunicipios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txtAPaterno.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        txtAPaterno.setForeground(new java.awt.Color(153, 153, 153));
        txtAPaterno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAPaterno.setText("Ingresa el apellido Paterno");
        txtAPaterno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtAPaterno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAPaternoMouseClicked(evt);
            }
        });
        txtAPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAPaternoActionPerformed(evt);
            }
        });
        txtAPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAPaternoKeyTyped(evt);
            }
        });

        lblAPaterno.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblAPaterno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAPaterno.setText("Apellido Paterno :");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Municipio :");

        txtCalle.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        txtCalle.setForeground(new java.awt.Color(153, 153, 153));
        txtCalle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCalle.setText("Ingresa el nombre de una calle");
        txtCalle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtCalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCalleMouseClicked(evt);
            }
        });
        txtCalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCalleActionPerformed(evt);
            }
        });
        txtCalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCalleKeyTyped(evt);
            }
        });

        btnC2.setBackground(new java.awt.Color(250, 176, 47));
        btnC2.setRoundBottomLeft(40);
        btnC2.setRoundBottomRight(40);
        btnC2.setRoundTopLeft(40);
        btnC2.setRoundTopRight(40);
        btnC2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnC2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnC2MouseExited(evt);
            }
        });

        btnAceptar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnAceptar.setText("ACEPTAR");
        btnAceptar.setBorder(null);
        btnAceptar.setContentAreaFilled(false);
        btnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAceptarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAceptarMouseExited(evt);
            }
        });
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnC2Layout = new javax.swing.GroupLayout(btnC2);
        btnC2.setLayout(btnC2Layout);
        btnC2Layout.setHorizontalGroup(
            btnC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnC2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnC2Layout.setVerticalGroup(
            btnC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        txtAMaterno.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        txtAMaterno.setForeground(new java.awt.Color(153, 153, 153));
        txtAMaterno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAMaterno.setText("Ingresa el apellido Materno");
        txtAMaterno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtAMaterno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAMaternoMouseClicked(evt);
            }
        });
        txtAMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAMaternoActionPerformed(evt);
            }
        });
        txtAMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAMaternoKeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Calle :");

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Numero :");

        txtNumeroCasa.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        txtNumeroCasa.setForeground(new java.awt.Color(153, 153, 153));
        txtNumeroCasa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumeroCasa.setText("Ingresa el numero de la casa");
        txtNumeroCasa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtNumeroCasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNumeroCasaMouseClicked(evt);
            }
        });
        txtNumeroCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroCasaActionPerformed(evt);
            }
        });
        txtNumeroCasa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroCasaKeyTyped(evt);
            }
        });

        btnC3.setBackground(new java.awt.Color(204, 204, 204));
        btnC3.setRoundBottomLeft(40);
        btnC3.setRoundBottomRight(40);
        btnC3.setRoundTopLeft(40);
        btnC3.setRoundTopRight(40);
        btnC3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnC3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnC3MouseExited(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnCancelar.setText("cancelar");
        btnCancelar.setBorder(null);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnC3Layout = new javax.swing.GroupLayout(btnC3);
        btnC3.setLayout(btnC3Layout);
        btnC3Layout.setHorizontalGroup(
            btnC3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnC3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnC3Layout.setVerticalGroup(
            btnC3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        cboPueblos.setBackground(new java.awt.Color(250, 176, 47));
        cboPueblos.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        cboPueblos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Pueblo :");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("RFC :");

        txtRfc.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        txtRfc.setForeground(new java.awt.Color(153, 153, 153));
        txtRfc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRfc.setText("Ingresa el RFC del cliente");
        txtRfc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtRfc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRfcMouseClicked(evt);
            }
        });
        txtRfc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRfcActionPerformed(evt);
            }
        });
        txtRfc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRfcKeyTyped(evt);
            }
        });

        lblFecha.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setText("Fecha de Nacimiento:");

        txtFecNac.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        txtFecNac.setForeground(new java.awt.Color(153, 153, 153));
        txtFecNac.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFecNac.setText("Año(98)  Mes(04)  Dia(15)");
        txtFecNac.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtFecNac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFecNacMouseClicked(evt);
            }
        });
        txtFecNac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFecNacActionPerformed(evt);
            }
        });
        txtFecNac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFecNacKeyTyped(evt);
            }
        });

        lblValidar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblValidar.setForeground(new java.awt.Color(204, 0, 0));
        lblValidar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValidar.setText("El RFC no es valido");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Tipo de persona:");

        cboPersona.setBackground(new java.awt.Color(250, 176, 47));
        cboPersona.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        cboPersona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fisica", "Moral" }));
        cboPersona.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(btnC3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblAMaterno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                .addComponent(lblAPaterno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNumeroTel)
                                .addComponent(txtNombre)
                                .addComponent(txtAPaterno)
                                .addComponent(txtAMaterno)
                                .addComponent(cboMunicipios, 0, 211, Short.MAX_VALUE)
                                .addComponent(cboPersona, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(0, 35, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cboPueblos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCalle)
                                .addComponent(txtNumeroCasa)
                                .addComponent(txtRfc)
                                .addComponent(lblValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFecNac, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboPersona, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroTel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboMunicipios, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboPueblos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtNumeroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFecha)
                    .addComponent(txtFecNac, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRfc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblValidar)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnC2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnC3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNumeroTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroTelActionPerformed

    private void txtCalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCalleActionPerformed

    private void btnAceptarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseEntered
            btnC2.setBackground(new Color(228,143,5));
    }//GEN-LAST:event_btnAceptarMouseEntered

    private void btnAceptarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseExited
       btnC2.setBackground(new Color(250,176,47));
    }//GEN-LAST:event_btnAceptarMouseExited

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        try{
            String nombreCliente = txtNombre.getText();
            String ApellidoPaterno = txtAPaterno.getText();
            String ApellidoMaterno = txtAMaterno.getText();
            String NumeroTelefonico = txtNumeroTel.getText();
            Pueblo puebloSeleccionado = (Pueblo) cboPueblos.getSelectedItem();
            int idPueblo = puebloSeleccionado.getId();
            int CodigoPostal = 1; //esto se va a quitar
            String calle = txtCalle.getText();
            String numero = txtNumeroCasa.getText();
            String rfc;
            if(txtRfc.getText().equals("Ingresa el RFC del cliente") || txtRfc.getText().isEmpty()){
    rfc = null;
}else{
    rfc = txtRfc.getText().toUpperCase();
    if (!rfc.matches("^[A-ZÑ&]{4}\\d{6}[A-Z0-9]{3}$")) {
        JOptionPane.showMessageDialog(null, "El RFC no tiene un formato válido. Debe tener este formato: MELM8305281H0");
        return;
    }
}
            
            if(fis == true){
            
            if(nombreCliente.isEmpty() || nombreCliente.equals("Ingresa un nombre")){
                JOptionPane.showMessageDialog(null, "No puedes dejar campos vacios, Ingresa un nombre");
            }
            if(ApellidoPaterno.isEmpty() || ApellidoPaterno.equals("Ingresa el Apellido Paterno")){
                JOptionPane.showMessageDialog(null, "No puedes dejar campos vacios, Ingresa un Apellido Paterno");
            }
            if(ApellidoMaterno.isEmpty() || ApellidoMaterno.equals("Ingresa el Apellido Materno")){
                JOptionPane.showMessageDialog(null, "No puedes dejar campos vacios, Ingresa un Apellido Materno");
            }
            if(NumeroTelefonico.isEmpty() || NumeroTelefonico.equals("Ingresa un numero Telefonico")){
                JOptionPane.showMessageDialog(null, "No puedes dejar campos vacios, Ingresa un Numero Telefonico");
            }
            if(calle.isEmpty() || calle.equals("Ingresa el nombre de una calle")){
                JOptionPane.showMessageDialog(null, "No puedes dejar campos vacios, Ingresa un nombre de calle");
            }
            if(numero.isEmpty() || numero.equals("Ingresa el numero de la casa")){
                JOptionPane.showMessageDialog(null, "No puedes dejar campos vacios, Ingresa un numero de casa");
            }else{
                int idDir = manejoclientes.insertarDireccion(calle, numero, idPueblo, CodigoPostal);
                idCliente = manejoclientes.insertarCliente(rfc, nombreCliente, ApellidoPaterno, ApellidoMaterno, NumeroTelefonico, idDir);
                JOptionPane.showMessageDialog(null, "Cliente Agregado");
                aceptado = true;
                this.dispose();
            }
            
            }
            if(mor == true){
            
            if(nombreCliente.isEmpty() || nombreCliente.equals("Ingresa un nombre")){
                JOptionPane.showMessageDialog(null, "No puedes dejar campos vacios, Ingresa un nombre");
            }
            if(NumeroTelefonico.isEmpty() || NumeroTelefonico.equals("Ingresa un numero Telefonico")){
                JOptionPane.showMessageDialog(null, "No puedes dejar campos vacios, Ingresa un Numero Telefonico");
            }
            if(calle.isEmpty() || calle.equals("Ingresa el nombre de una calle")){
                JOptionPane.showMessageDialog(null, "No puedes dejar campos vacios, Ingresa un nombre de calle");
            }
            if(numero.isEmpty() || numero.equals("Ingresa el numero de la casa")){
                JOptionPane.showMessageDialog(null, "No puedes dejar campos vacios, Ingresa un numero de casa");
            }else{
                int idDir = manejoclientes.insertarDireccion(calle, numero, idPueblo, CodigoPostal);
                idCliente = manejoclientes.insertarCliente(rfc, nombreCliente, ApellidoPaterno, ApellidoMaterno, NumeroTelefonico, idDir);
                JOptionPane.showMessageDialog(null, "Cliente Agregado");
                aceptado = true;
                this.dispose();
            }
            }
            
        }catch(SQLException e){
            
        }
      
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnC2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnC2MouseEntered
       
    }//GEN-LAST:event_btnC2MouseEntered

    private void btnC2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnC2MouseExited
       
    }//GEN-LAST:event_btnC2MouseExited

    private void txtAPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAPaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAPaternoActionPerformed

    private void txtAMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAMaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAMaternoActionPerformed

    private void txtNumeroCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroCasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroCasaActionPerformed

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        btnC3.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
       btnC3.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_btnCancelarMouseExited

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnC3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnC3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnC3MouseEntered

    private void btnC3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnC3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnC3MouseExited

    private void txtNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseClicked
        if(!e1){
        txtNombre.setText("");
        txtNombre.setForeground(Color.BLACK);
        e1 = true;
        }
    }//GEN-LAST:event_txtNombreMouseClicked

    private void txtAPaternoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAPaternoMouseClicked
        if(!e2){
        txtAPaterno.setText("");
        txtAPaterno.setForeground(Color.BLACK);
        e2 = true;
        }
    }//GEN-LAST:event_txtAPaternoMouseClicked

    private void txtAMaternoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAMaternoMouseClicked
        if(!e3){
        txtAMaterno.setText("");
        txtAMaterno.setForeground(Color.BLACK);
        e3 = true;
        }
    }//GEN-LAST:event_txtAMaternoMouseClicked

    private void txtNumeroTelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNumeroTelMouseClicked
        if(!e4){
        txtNumeroTel.setText("");
        txtNumeroTel.setForeground(Color.BLACK);
        e4 = true;
        }
    }//GEN-LAST:event_txtNumeroTelMouseClicked

    private void txtCalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCalleMouseClicked
        if(!e5){
        txtCalle.setText("");
        txtCalle.setForeground(Color.BLACK);
        e5 = true;
        }
    }//GEN-LAST:event_txtCalleMouseClicked

    private void txtNumeroCasaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNumeroCasaMouseClicked
        if(!e6){
        txtNumeroCasa.setText("");
        txtNumeroCasa.setForeground(Color.BLACK);
        e6 = true;
        }
    }//GEN-LAST:event_txtNumeroCasaMouseClicked

    private void txtRfcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRfcMouseClicked
       if(!e7){
       txtRfc.setText("");
       txtRfc.setForeground(Color.BLACK);
       e7 = true;
       }
    }//GEN-LAST:event_txtRfcMouseClicked

    private void txtRfcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRfcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRfcActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char c = evt.getKeyChar();
                if (!Character.isLetter(c)) {
                    evt.consume(); // Ignorar el carácter
                }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtAPaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAPaternoKeyTyped
        char c = evt.getKeyChar();
                if (!Character.isLetter(c)) {
                    evt.consume(); // Ignorar el carácter
                }
    }//GEN-LAST:event_txtAPaternoKeyTyped

    private void txtAMaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAMaternoKeyTyped
        char c = evt.getKeyChar();
                if (!Character.isLetter(c)) {
                    evt.consume(); // Ignorar el carácter
                }
    }//GEN-LAST:event_txtAMaternoKeyTyped

    private void txtNumeroTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroTelKeyTyped
        char c = evt.getKeyChar();
                if (!Character.isDigit(c)) {
                    evt.consume(); // Ignorar el carácter
                }
    }//GEN-LAST:event_txtNumeroTelKeyTyped

    private void txtCalleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCalleKeyTyped
        char c = evt.getKeyChar();
                if (!Character.isLetterOrDigit(c) && !Character.isWhitespace(c)) {
                    evt.consume(); // Ignorar el carácter
                }
    }//GEN-LAST:event_txtCalleKeyTyped

    private void txtNumeroCasaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroCasaKeyTyped
        char c = evt.getKeyChar();
                if (!Character.isDigit(c)) {
                    evt.consume(); // Ignorar el carácter
                }
    }//GEN-LAST:event_txtNumeroCasaKeyTyped

    private void txtRfcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRfcKeyTyped
        char c = evt.getKeyChar();
                if (!Character.isLetterOrDigit(c) && !Character.isWhitespace(c)) {
                    evt.consume(); // Ignorar el carácter
                }
    }//GEN-LAST:event_txtRfcKeyTyped

    private void txtFecNacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFecNacMouseClicked
        if(!e8){
       txtFecNac.setText("");
       txtFecNac.setForeground(Color.BLACK);
       e8 = true;
       }
    }//GEN-LAST:event_txtFecNacMouseClicked

    private void txtFecNacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFecNacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFecNacActionPerformed

    private void txtFecNacKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFecNacKeyTyped
        char c = evt.getKeyChar();
                if (!Character.isDigit(c) && !Character.isWhitespace(c) ) {
                    evt.consume(); // Ignorar el carácter
                }
    }//GEN-LAST:event_txtFecNacKeyTyped

    public boolean isAceptado() {
        return aceptado;
    }

    public void setAceptado(boolean aceptado) {
        this.aceptado = aceptado;
    }

    public int getIdCliente() {
        return idCliente;
    }

    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }

    private void validarYActualizarBoton() {
        String nombre = txtNombre.getText();
        String apellidoPaterno = txtAPaterno.getText();
        String apellidoMaterno = txtAMaterno.getText();
        String fechaNacimiento = txtFecNac.getText();
        String rfcIngresado = txtRfc.getText();


        boolean valido = validarRFCFisica(nombre, apellidoPaterno, apellidoMaterno, fechaNacimiento, rfcIngresado);
        boolean val2 = validarRFCMoral(nombre,fechaNacimiento,rfcIngresado);
        btnAceptar.setEnabled(valido || val2);
        btnC2.setEnabled(valido || val2);
        if(valido || val2){
        lblValidar.setText("El RFC es valido");
        lblValidar.setForeground(new Color(0,153,0));
        }else{
            lblValidar.setText("El RFC no es valido");
        lblValidar.setForeground(new Color(204,0,0));
        }
    }

    public boolean validarRFCFisica(String nombre, String apellidoPaterno, String apellidoMaterno, String fechaNacimiento, String rfcIngresado) {
    if (nombre.isEmpty() || apellidoPaterno.length() < 2 || apellidoMaterno.isEmpty()
            || fechaNacimiento.isEmpty() || rfcIngresado.length() != 13) {
        return false;
    }

    char inicialNombre = nombre.trim().toUpperCase().charAt(0);
    char inicialApellidoMaterno = apellidoMaterno.trim().toUpperCase().charAt(0);
    String inicialesApellidoPaterno = apellidoPaterno.trim().toUpperCase().substring(0, 2);
    String fechaSinEspacios = fechaNacimiento.replaceAll("\\s+", "");

    String rfcEsperado = inicialesApellidoPaterno + inicialApellidoMaterno + inicialNombre + fechaSinEspacios;
    String rfcInicio = rfcIngresado.trim().toUpperCase().substring(0, 10);

    return rfcEsperado.equals(rfcInicio);
}
    
    public boolean validarRFCMoral(String nombre, String fechaNacimiento, String rfcIngresado) {
    if (nombre.isEmpty() || fechaNacimiento.isEmpty() || rfcIngresado.length() != 12) {
        return false;
    }

    String inicialNombre = nombre.trim().toUpperCase().substring(0, 3);
    String fechaSinEspacios = fechaNacimiento.replaceAll("\\s+", "");

    String rfcEsperado = inicialNombre + fechaSinEspacios;
    String rfcInicio = rfcIngresado.trim().toUpperCase().substring(0, 9);

    return rfcEsperado.equals(rfcInicio);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarClientePV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarClientePV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarClientePV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarClientePV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AgregarClientePV dialog = new AgregarClientePV(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private UI.PanelRound btnC2;
    private UI.PanelRound btnC3;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<Municipio> cboMunicipios;
    private javax.swing.JComboBox<String> cboPersona;
    private javax.swing.JComboBox<Pueblo> cboPueblos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAMaterno;
    private javax.swing.JLabel lblAPaterno;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblValidar;
    private UI.PanelRound panelRound1;
    private javax.swing.JTextField txtAMaterno;
    private javax.swing.JTextField txtAPaterno;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtFecNac;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroCasa;
    private javax.swing.JTextField txtNumeroTel;
    private javax.swing.JTextField txtRfc;
    // End of variables declaration//GEN-END:variables
}
