/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UIEmergentes;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author salin
 */
public class Devolucion extends javax.swing.JDialog {

    /**
     * Creates new form Devolucion
     */
    public Devolucion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/logo6.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panelRound1 = new UI.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        obtUsuario = new javax.swing.JTextField();
        obtUsuario2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        obtUsuario5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        obtUsuario7 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        obtUsuario8 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btnC2 = new UI.PanelRound();
        btnCan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(250, 176, 47));
        panelRound1.setRoundBottomLeft(45);
        panelRound1.setRoundBottomRight(45);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Devolucion");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        jPanel2.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, -1));

        obtUsuario.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        obtUsuario.setForeground(new java.awt.Color(102, 102, 102));
        obtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        obtUsuario.setText("Codigo");
        obtUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        obtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obtUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(obtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 211, 34));

        obtUsuario2.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        obtUsuario2.setForeground(new java.awt.Color(102, 102, 102));
        obtUsuario2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        obtUsuario2.setText("Nombre");
        obtUsuario2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        obtUsuario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obtUsuario2ActionPerformed(evt);
            }
        });
        jPanel2.add(obtUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 211, 34));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setText("Codigo del producto");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, 21));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setText("Nombre del producto");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        obtUsuario5.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        obtUsuario5.setForeground(new java.awt.Color(102, 102, 102));
        obtUsuario5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        obtUsuario5.setText("Motivo");
        obtUsuario5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        obtUsuario5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obtUsuario5ActionPerformed(evt);
            }
        });
        jPanel2.add(obtUsuario5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 450, 70));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel9.setText("Motivo de devolucion");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        obtUsuario7.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        obtUsuario7.setForeground(new java.awt.Color(102, 102, 102));
        obtUsuario7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        obtUsuario7.setText("Cantidad");
        obtUsuario7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        obtUsuario7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obtUsuario7ActionPerformed(evt);
            }
        });
        jPanel2.add(obtUsuario7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 211, 34));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel13.setText("Cantidad a devolver");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, 20));

        obtUsuario8.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        obtUsuario8.setForeground(new java.awt.Color(102, 102, 102));
        obtUsuario8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        obtUsuario8.setText("Fecha ");
        obtUsuario8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        obtUsuario8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obtUsuario8ActionPerformed(evt);
            }
        });
        jPanel2.add(obtUsuario8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 211, 34));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel15.setText("Fecha de devolucion");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, 20));

        btnC2.setBackground(new java.awt.Color(250, 176, 47));
        btnC2.setRoundBottomLeft(40);
        btnC2.setRoundBottomRight(40);
        btnC2.setRoundTopLeft(40);
        btnC2.setRoundTopRight(40);
        btnC2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnC2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnC2MouseExited(evt);
            }
        });

        btnCan.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnCan.setText("ACEPTAR");
        btnCan.setBorder(null);
        btnCan.setContentAreaFilled(false);
        btnCan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCanMouseExited(evt);
            }
        });
        btnCan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnC2Layout = new javax.swing.GroupLayout(btnC2);
        btnC2.setLayout(btnC2Layout);
        btnC2Layout.setHorizontalGroup(
            btnC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnC2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnCan)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        btnC2Layout.setVerticalGroup(
            btnC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnC2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCan, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(btnC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void obtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obtUsuarioActionPerformed

    private void obtUsuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obtUsuario2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obtUsuario2ActionPerformed

    private void obtUsuario5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obtUsuario5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obtUsuario5ActionPerformed

    private void obtUsuario7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obtUsuario7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obtUsuario7ActionPerformed

    private void obtUsuario8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obtUsuario8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obtUsuario8ActionPerformed

    private void btnCanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCanMouseEntered
        btnC2.setBackground(new Color(228,143,5)); //[250,176,47]
    }//GEN-LAST:event_btnCanMouseEntered

    private void btnCanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCanMouseExited
        btnC2.setBackground(new Color(250,176,47));
    }//GEN-LAST:event_btnCanMouseExited

    private void btnCanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCanActionPerformed

    private void btnC2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnC2MouseEntered
        btnC2.setBackground(new Color(228,143,5)); //[250,176,47]
    }//GEN-LAST:event_btnC2MouseEntered

    private void btnC2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnC2MouseExited
        btnC2.setBackground(new Color(250,176,47));
    }//GEN-LAST:event_btnC2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Devolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Devolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Devolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Devolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Devolucion dialog = new Devolucion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private UI.PanelRound btnC2;
    private javax.swing.JButton btnCan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField obtUsuario;
    private javax.swing.JTextField obtUsuario2;
    private javax.swing.JTextField obtUsuario5;
    private javax.swing.JTextField obtUsuario7;
    private javax.swing.JTextField obtUsuario8;
    private UI.PanelRound panelRound1;
    // End of variables declaration//GEN-END:variables
}
