/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UIEmergentes;

import java.awt.Color;
import ManejoTablas.*;
import java.sql.SQLException;
import java.time.Year;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author salin
 */
public class EscogerAnio extends javax.swing.JDialog {
    private ManejoInventario mi = new ManejoInventario();
    private int anioEscogido;
    /**
     * Creates new form AgregarProductos
     */
    public EscogerAnio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/logo6.png")).getImage());
        DefaultComboBoxModel<String> modeloAnios = new DefaultComboBoxModel<>(); // Modelo de String

    // Definir el rango de años
    int anioInicio = 2020;
    int anioActual = Year.now().getValue(); // Obtiene el año actual dinámicamente

    // Llenar el modelo con los años del rango (convertidos a String)
    for (int anio = anioInicio; anio <= anioActual; anio++) {
        modeloAnios.addElement(String.valueOf(anio)); // Convertir a String
    }

    cboAnio.setModel(modeloAnios);
    cboAnio.setSelectedItem(String.valueOf(anioActual)); // Convertir a String al seleccionar
        
    }
    

    public int getAnioEscogido() {
        return anioEscogido;
    }

    public void setAnioEscogido(int anioEscogido) {
        this.anioEscogido = anioEscogido;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelRound1 = new UI.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        BtnA = new UI.PanelRound();
        btnAce = new javax.swing.JButton();
        btnC = new UI.PanelRound();
        btnCan = new javax.swing.JButton();
        cboAnio = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        panelRound1.setBackground(new java.awt.Color(250, 176, 47));
        panelRound1.setRoundBottomLeft(30);
        panelRound1.setRoundBottomRight(30);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Escoge el año");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        BtnA.setBackground(new java.awt.Color(204, 204, 204));
        BtnA.setRoundBottomLeft(40);
        BtnA.setRoundBottomRight(40);
        BtnA.setRoundTopLeft(40);
        BtnA.setRoundTopRight(40);
        BtnA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnAMouseExited(evt);
            }
        });

        btnAce.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnAce.setText("Cancelar");
        btnAce.setBorder(null);
        btnAce.setContentAreaFilled(false);
        btnAce.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAceMouseExited(evt);
            }
        });
        btnAce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BtnALayout = new javax.swing.GroupLayout(BtnA);
        BtnA.setLayout(BtnALayout);
        BtnALayout.setHorizontalGroup(
            BtnALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAce, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addContainerGap())
        );
        BtnALayout.setVerticalGroup(
            BtnALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAce, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        btnC.setBackground(new java.awt.Color(250, 176, 47));
        btnC.setRoundBottomLeft(40);
        btnC.setRoundBottomRight(40);
        btnC.setRoundTopLeft(40);
        btnC.setRoundTopRight(40);
        btnC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCMouseExited(evt);
            }
        });

        btnCan.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnCan.setText("ACEPTAR");
        btnCan.setBorder(null);
        btnCan.setContentAreaFilled(false);
        btnCan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCanMouseExited(evt);
            }
        });
        btnCan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnCLayout = new javax.swing.GroupLayout(btnC);
        btnC.setLayout(btnCLayout);
        btnCLayout.setHorizontalGroup(
            btnCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCan, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnCLayout.setVerticalGroup(
            btnCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCan, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        cboAnio.setBackground(new java.awt.Color(250, 176, 47));
        cboAnio.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        cboAnio.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(BtnA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cboAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cboAnio, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnAceActionPerformed

    private void BtnAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAMouseEntered
        BtnA.setBackground(new Color(153,153,153)); //[250,176,47]
    }//GEN-LAST:event_BtnAMouseEntered

    private void BtnAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAMouseExited
        BtnA.setBackground(new Color(204,204,204)); //[250,176,47]
    }//GEN-LAST:event_BtnAMouseExited

    private void btnCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCMouseEntered
        btnC.setBackground(new Color(228,143,5)); //[250,176,47]
    }//GEN-LAST:event_btnCMouseEntered

    private void btnCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCMouseExited
        btnC.setBackground(new Color(250,176,47));
    }//GEN-LAST:event_btnCMouseExited

    private void btnAceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceMouseEntered
        BtnA.setBackground(new Color(153,153,153)); //[250,176,47]
    }//GEN-LAST:event_btnAceMouseEntered

    private void btnAceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceMouseExited
        BtnA.setBackground(new Color(204,204,204)); //[250,176,47]
    }//GEN-LAST:event_btnAceMouseExited

    private void btnCanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCanMouseEntered
        btnC.setBackground(new Color(228,143,5)); //[250,176,47]
    }//GEN-LAST:event_btnCanMouseEntered

    private void btnCanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCanMouseExited
        btnC.setBackground(new Color(250,176,47));
    }//GEN-LAST:event_btnCanMouseExited

    private void btnCanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanActionPerformed
        String a = cboAnio.getSelectedItem().toString();
        int anio = Integer.parseInt(a);
        anioEscogido = anio;
        
        this.dispose();
    }//GEN-LAST:event_btnCanActionPerformed

   


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscogerAnio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscogerAnio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscogerAnio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscogerAnio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EscogerAnio dialog = new EscogerAnio(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private UI.PanelRound BtnA;
    private javax.swing.JButton btnAce;
    private UI.PanelRound btnC;
    private javax.swing.JButton btnCan;
    private javax.swing.JComboBox<String> cboAnio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private UI.PanelRound panelRound1;
    // End of variables declaration//GEN-END:variables
}
