/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UIEmergentes;

import ManejoTablas.*;
import Modelo.*;
import java.awt.Color;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author salin
 */
public class PagarVenta extends javax.swing.JDialog {
    private boolean aceptado, e1,e2,e3,e4,existeCl;
    
    private int idPagote, idVenta, cant, idCliente;
    private JList<Integer> lstID; // Referencia a la JList desde donde obtendrás los IDs
    private DefaultListModel<Integer> modeloListaID; // Modelo de la JList
    private JList<String> lstCant; // Referencia a la JList desde donde obtendrás los IDs
    private DefaultListModel<String> modeloListaCant; // Modelo de la JList
    private HacerVentas hacerventa = new HacerVentas();
    private ManejoInventario manejoinventario = new ManejoInventario();
    private ManejoProductos manejoproductos = new ManejoProductos();
    private ManejoClientes manejoclientes = new ManejoClientes();
    private ManejoVentas manejoventas = new ManejoVentas();
    /**
     * Creates new form PagarVenta
     */
    public PagarVenta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        e1 = false; 
        e2 = false; 
        e3 = false; 
        e4 = false;
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/logo6.png")).getImage());
        pnlBancario.setVisible(false);
        sprRecibido.setBackground(new Color(204,204,204));
        sprRecibido.setOpaque(true);
        
        
    }

    public PagarVenta() {
    }
    
    
    
    public void obtenerTotal(String total){
        lblTotal.setText(total);
        lblTotal2.setText(total);
        calcularCambio();
    }
    
    public void definirCantidadMin(Double n){
        sprRecibido.setModel(new javax.swing.SpinnerNumberModel((Double)n, (Double)n, null, 1.0));
        DecimalFormat decimalFormat = new DecimalFormat("0.00");
        NumberFormatter formatter = new NumberFormatter(decimalFormat);
        JSpinner.NumberEditor editor = new JSpinner.NumberEditor(sprRecibido, decimalFormat.toPattern());
        sprRecibido.setEditor(editor);
        //pcact = n;
    }
    
    private void calcularCambio(){
        Double tot = Double.parseDouble(lblTotal.getText());
        Double rec = Double.parseDouble(sprRecibido.getValue().toString());
        if(rec<tot){lblCambio.setText("-");}
        else{
        Double cambio = rec - tot;
        lblCambio.setText(String.format("%.2f", cambio));
        }
    }
    
    
     public boolean isAceptado() {
        return aceptado;
    }

    public int getIdPag() {
        return idPagote;
    }

    public void setIdPag(int idPag) {
        this.idPagote = idPag;
    }


    public int getCant() {
        return cant;
    }

    public void setCant(int cant) {
        this.cant = cant;
    }

    public int getIdCliente() {
        return idCliente;
    }

    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel22 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        panelRound1 = new UI.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cboForma = new javax.swing.JComboBox<>();
        pnlAceptar = new UI.PanelRound();
        btnAceptar = new javax.swing.JButton();
        pnlCancelar = new UI.PanelRound();
        btnCancelar = new javax.swing.JButton();
        pnlEfectivo = new UI.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lblCliente = new javax.swing.JLabel();
        sprRecibido = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        chkFacturar = new javax.swing.JCheckBox();
        btnBuscar = new UI.PanelRound();
        btnB = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btnAgregarCliente = new UI.PanelRound();
        btnA = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblCambio = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        pnlBancario = new UI.PanelRound();
        jLabel12 = new javax.swing.JLabel();
        lblTotal2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtNombre2 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        chkFacturar2 = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        lblCliente2 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        btnBuscar2 = new UI.PanelRound();
        btnB1 = new javax.swing.JLabel();
        btnAgregarCliente2 = new UI.PanelRound();
        btnA1 = new javax.swing.JLabel();

        jLabel22.setText("jLabel22");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(250, 176, 47));
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ingresa los datos de pago");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Forma de pago :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 86, -1, -1));

        cboForma.setBackground(new java.awt.Color(250, 176, 47));
        cboForma.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cboForma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Bancario" }));
        cboForma.setBorder(null);
        cboForma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cboForma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboFormaActionPerformed(evt);
            }
        });
        jPanel1.add(cboForma, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 84, 230, -1));

        pnlAceptar.setBackground(new java.awt.Color(250, 176, 47));
        pnlAceptar.setRoundBottomLeft(60);
        pnlAceptar.setRoundBottomRight(60);
        pnlAceptar.setRoundTopLeft(60);
        pnlAceptar.setRoundTopRight(60);

        btnAceptar.setBackground(new java.awt.Color(250, 176, 47));
        btnAceptar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.setBorder(null);
        btnAceptar.setBorderPainted(false);
        btnAceptar.setContentAreaFilled(false);
        btnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAceptarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAceptarMouseExited(evt);
            }
        });
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAceptarLayout = new javax.swing.GroupLayout(pnlAceptar);
        pnlAceptar.setLayout(pnlAceptarLayout);
        pnlAceptarLayout.setHorizontalGroup(
            pnlAceptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAceptarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlAceptarLayout.setVerticalGroup(
            pnlAceptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAceptarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(pnlAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        pnlCancelar.setBackground(new java.awt.Color(204, 204, 204));
        pnlCancelar.setRoundBottomLeft(60);
        pnlCancelar.setRoundBottomRight(60);
        pnlCancelar.setRoundTopLeft(60);
        pnlCancelar.setRoundTopRight(60);

        btnCancelar.setBackground(new java.awt.Color(204, 204, 204));
        btnCancelar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(null);
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCancelarLayout = new javax.swing.GroupLayout(pnlCancelar);
        pnlCancelar.setLayout(pnlCancelarLayout);
        pnlCancelarLayout.setHorizontalGroup(
            pnlCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCancelarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlCancelarLayout.setVerticalGroup(
            pnlCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCancelarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(pnlCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, -1, -1));

        pnlEfectivo.setBackground(new java.awt.Color(204, 204, 204));
        pnlEfectivo.setRoundBottomLeft(45);
        pnlEfectivo.setRoundBottomRight(45);
        pnlEfectivo.setRoundTopLeft(45);
        pnlEfectivo.setRoundTopRight(45);
        pnlEfectivo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Total a Pagar :");
        pnlEfectivo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 22, -1, -1));

        lblTotal.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotal.setText("-");
        pnlEfectivo.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 22, 137, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        pnlEfectivo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 47, 167, 10));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel5.setText("$");
        pnlEfectivo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Recibido:");
        pnlEfectivo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 65, 111, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel8.setText("$");
        pnlEfectivo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 63, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        pnlEfectivo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 92, 167, 10));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Cliente :");
        pnlEfectivo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 70, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel9.setText("$");
        pnlEfectivo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 108, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        pnlEfectivo.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 270, 210, 10));

        lblCliente.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCliente.setText("-");
        pnlEfectivo.add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 200, -1));

        sprRecibido.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        sprRecibido.setBorder(null);
        sprRecibido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sprRecibido.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sprRecibidoStateChanged(evt);
            }
        });
        sprRecibido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sprRecibidoMouseClicked(evt);
            }
        });
        pnlEfectivo.add(sprRecibido, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 63, 105, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setText("Facturar :");
        pnlEfectivo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        chkFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFacturarActionPerformed(evt);
            }
        });
        pnlEfectivo.add(chkFacturar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        btnBuscar.setBackground(new java.awt.Color(250, 176, 47));
        btnBuscar.setEnabled(false);
        btnBuscar.setRoundBottomLeft(50);
        btnBuscar.setRoundBottomRight(50);
        btnBuscar.setRoundTopLeft(50);
        btnBuscar.setRoundTopRight(50);

        btnB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar30.png"))); // NOI18N
        btnB.setToolTipText("");
        btnB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnB.setEnabled(false);
        btnB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnBuscarLayout = new javax.swing.GroupLayout(btnBuscar);
        btnBuscar.setLayout(btnBuscarLayout);
        btnBuscarLayout.setHorizontalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        btnBuscarLayout.setVerticalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnB, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlEfectivo.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 40, 40));

        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Cambio:");
        pnlEfectivo.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 110, 111, -1));

        jLabel23.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Buscar");
        pnlEfectivo.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 70, -1));

        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Añadir");
        pnlEfectivo.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 70, -1));

        jLabel25.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Cliente");
        pnlEfectivo.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 70, -1));

        btnAgregarCliente.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregarCliente.setEnabled(false);
        btnAgregarCliente.setRoundBottomLeft(50);
        btnAgregarCliente.setRoundBottomRight(50);
        btnAgregarCliente.setRoundTopLeft(50);
        btnAgregarCliente.setRoundTopRight(50);
        btnAgregarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarClienteMouseExited(evt);
            }
        });

        btnA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar30.png"))); // NOI18N
        btnA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnA.setEnabled(false);
        btnA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnAgregarClienteLayout = new javax.swing.GroupLayout(btnAgregarCliente);
        btnAgregarCliente.setLayout(btnAgregarClienteLayout);
        btnAgregarClienteLayout.setHorizontalGroup(
            btnAgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        btnAgregarClienteLayout.setVerticalGroup(
            btnAgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnA, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlEfectivo.add(btnAgregarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 40, 40));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Cliente");
        pnlEfectivo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 70, -1));

        lblCambio.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblCambio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCambio.setText("-");
        pnlEfectivo.add(lblCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 110, 146, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        pnlEfectivo.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 135, 167, 10));

        jPanel1.add(pnlEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 340, 290));

        pnlBancario.setBackground(new java.awt.Color(250, 176, 47));
        pnlBancario.setMinimumSize(new java.awt.Dimension(317, 230));
        pnlBancario.setRoundBottomLeft(45);
        pnlBancario.setRoundBottomRight(45);
        pnlBancario.setRoundTopLeft(45);
        pnlBancario.setRoundTopRight(45);
        pnlBancario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setText("Total a Pagar :");
        pnlBancario.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        lblTotal2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblTotal2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotal2.setText("-");
        pnlBancario.add(lblTotal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 137, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel13.setText("$");
        pnlBancario.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("contacto");
        pnlBancario.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 111, -1));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Cliente");
        pnlBancario.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 111, -1));

        txtNombre2.setBackground(new java.awt.Color(250, 176, 47));
        txtNombre2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtNombre2.setForeground(new java.awt.Color(102, 102, 102));
        txtNombre2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre2.setText("Ingresa un nombre");
        txtNombre2.setBorder(null);
        txtNombre2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtNombre2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombre2MouseClicked(evt);
            }
        });
        txtNombre2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombre2KeyTyped(evt);
            }
        });
        pnlBancario.add(txtNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 140, 30));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        pnlBancario.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 140, 10));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        pnlBancario.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 134, 10));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Nombre del");
        pnlBancario.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 111, -1));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Numero de");
        pnlBancario.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 111, -1));

        txtNumero.setBackground(new java.awt.Color(250, 176, 47));
        txtNumero.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtNumero.setForeground(new java.awt.Color(102, 102, 102));
        txtNumero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumero.setText("Ingresa un numero");
        txtNumero.setBorder(null);
        txtNumero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtNumero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNumeroMouseClicked(evt);
            }
        });
        txtNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroKeyTyped(evt);
            }
        });
        pnlBancario.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 150, 30));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        pnlBancario.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 140, 10));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel11.setText("Facturar :");
        pnlBancario.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        chkFacturar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFacturar2ActionPerformed(evt);
            }
        });
        pnlBancario.add(chkFacturar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Cliente :");
        pnlBancario.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 70, -1));

        lblCliente2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblCliente2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCliente2.setText("-");
        pnlBancario.add(lblCliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 200, -1));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        pnlBancario.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 210, 10));

        jLabel26.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Buscar");
        pnlBancario.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 70, -1));

        jLabel27.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Cliente");
        pnlBancario.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 70, -1));

        jLabel28.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Añadir");
        pnlBancario.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 70, -1));

        jLabel29.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Cliente");
        pnlBancario.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 70, -1));

        btnBuscar2.setBackground(new java.awt.Color(204, 204, 204));
        btnBuscar2.setEnabled(false);
        btnBuscar2.setRoundBottomLeft(50);
        btnBuscar2.setRoundBottomRight(50);
        btnBuscar2.setRoundTopLeft(50);
        btnBuscar2.setRoundTopRight(50);

        btnB1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar30.png"))); // NOI18N
        btnB1.setToolTipText("");
        btnB1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnB1.setEnabled(false);
        btnB1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnB1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnB1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnB1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnBuscar2Layout = new javax.swing.GroupLayout(btnBuscar2);
        btnBuscar2.setLayout(btnBuscar2Layout);
        btnBuscar2Layout.setHorizontalGroup(
            btnBuscar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnB1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        btnBuscar2Layout.setVerticalGroup(
            btnBuscar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnB1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlBancario.add(btnBuscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 40, 40));

        btnAgregarCliente2.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregarCliente2.setEnabled(false);
        btnAgregarCliente2.setRoundBottomLeft(50);
        btnAgregarCliente2.setRoundBottomRight(50);
        btnAgregarCliente2.setRoundTopLeft(50);
        btnAgregarCliente2.setRoundTopRight(50);
        btnAgregarCliente2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarCliente2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarCliente2MouseExited(evt);
            }
        });

        btnA1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar30.png"))); // NOI18N
        btnA1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnA1.setEnabled(false);
        btnA1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnA1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnA1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnA1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnAgregarCliente2Layout = new javax.swing.GroupLayout(btnAgregarCliente2);
        btnAgregarCliente2.setLayout(btnAgregarCliente2Layout);
        btnAgregarCliente2Layout.setHorizontalGroup(
            btnAgregarCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnA1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        btnAgregarCliente2Layout.setVerticalGroup(
            btnAgregarCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnA1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlBancario.add(btnAgregarCliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 40, 40));

        jPanel1.add(pnlBancario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 340, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cboFormaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboFormaActionPerformed
        String sel = cboForma.getSelectedItem().toString();
        if(sel.equals("Efectivo")){
            pnlEfectivo.setVisible(true);
            pnlBancario.setVisible(false);
        }else{
            pnlBancario.setVisible(true);
            pnlEfectivo.setVisible(false);
        }
    }//GEN-LAST:event_cboFormaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
        aceptado = false;
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void sprRecibidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sprRecibidoMouseClicked
        
    }//GEN-LAST:event_sprRecibidoMouseClicked

    private void sprRecibidoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sprRecibidoStateChanged
       calcularCambio();
    }//GEN-LAST:event_sprRecibidoStateChanged

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String sel = cboForma.getSelectedItem().toString();
boolean debeFacturar = chkFacturar.isSelected() || chkFacturar2.isSelected();

try {
    if (sel.equals("Efectivo")) {
        if (debeFacturar) {
            if (lblCliente.getText().equals("-")) {
                JOptionPane.showMessageDialog(null, "Selecciona un cliente para facturar");
            } else {
                JOptionPane.showMessageDialog(null, "Venta Realizada Exitosamente, Se ha generado la factura en la carpeta FACTURAS dentro del escritorio");
                
                hacerVenta(); // Llamada a hacerVenta después de generar la factura (si es necesario)
                generarFactura();
                aceptado = true;
                this.dispose();
            }
        } else {
            hacerVenta();
            JOptionPane.showMessageDialog(null, "Venta Realizada Exitosamente");
            aceptado = true;
            this.dispose();
        } 
    } else { // Forma de pago bancaria
        
        if (debeFacturar) {
            if (lblCliente2.getText().equals("-")) {
                JOptionPane.showMessageDialog(null, "Selecciona un cliente para facturar");
            } else {
                JOptionPane.showMessageDialog(null, "Venta Realizada Exitosamente, Se ha generado la factura en la carpeta FACTURAS dentro del escritorio");
                
                hacerVentaBancaria();
                generarFactura();
                aceptado = true;
                this.dispose();
            }
        } else {
            if((!txtNombre2.getText().equals("Ingresa un nombre") && !txtNombre2.getText().isEmpty()) && (!txtNumero.getText().equals("Ingresa un numero") && !txtNumero.getText().isEmpty())){
            hacerVentaBancaria();
            JOptionPane.showMessageDialog(null, "Venta Realizada Exitosamente");
            aceptado = true;
            this.dispose();}else{
                JOptionPane.showMessageDialog(null, "Rellena todos los campos");
            }
        }
    }
} catch (SQLException ex) {
    JOptionPane.showMessageDialog(null, "Error al realizar la venta");
}
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtNombre2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombre2MouseClicked
        txtNombre2.setText("");
        txtNombre2.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtNombre2MouseClicked

    private void txtNumeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNumeroMouseClicked
        txtNumero.setText("");
        txtNumero.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtNumeroMouseClicked

    private void btnAceptarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseEntered
        pnlAceptar.setBackground(new Color(228,143,5));
    }//GEN-LAST:event_btnAceptarMouseEntered

    private void btnAceptarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseExited
        pnlAceptar.setBackground(new Color(250,176,47));
    }//GEN-LAST:event_btnAceptarMouseExited

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        pnlCancelar.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        pnlCancelar.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_btnCancelarMouseExited

    private void chkFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFacturarActionPerformed
        
        if(!chkFacturar.isSelected()){
            e1 = false;
            e2 = false;
            btnA.setEnabled(false);
            btnB.setEnabled(false);
        }else{
            btnAgregarCliente.setEnabled(true);
            btnBuscar.setEnabled(true);
            btnA.setEnabled(true);
            btnB.setEnabled(true);
            e1 = true;
            e2 = true;
            chkFacturar2.setSelected(false);
        }
    }//GEN-LAST:event_chkFacturarActionPerformed

    private void btnBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBMouseClicked
        if(e1 == true){
        BuscarClientesPV bc = new BuscarClientesPV(null, true);
        bc.setVisible(true);
        if(bc.isAceptado()){
            lblCliente.setText(bc.getNombreCliente());
            System.out.println("Id Cliente : "+bc.getIdCliente());
            idCliente = bc.getIdCliente();
        }
        }
    }//GEN-LAST:event_btnBMouseClicked

    private void btnBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBMouseEntered
        btnBuscar.setBackground(new Color(228,143,5));
    }//GEN-LAST:event_btnBMouseEntered

    private void btnBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBMouseExited
        btnBuscar.setBackground(new Color(250,176,47));
    }//GEN-LAST:event_btnBMouseExited

    private void btnAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAMouseClicked
        if(e1 == true){
        AgregarClientePV ac = new AgregarClientePV(null, true);
        ac.setVisible(true);
        if(ac.isAceptado()){
            try {
                Cliente c = manejoclientes.buscarClientePorId(ac.getIdCliente());
                lblCliente.setText(c.getNombre()+" "+c.getaPaterno()+" "+c.getaMaterno());
                idCliente = ac.getIdCliente();
            } catch (SQLException ex) {}
        }}
    }//GEN-LAST:event_btnAMouseClicked

    private void btnAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAMouseEntered
        btnAgregarCliente.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_btnAMouseEntered

    private void btnAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAMouseExited
        btnAgregarCliente.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnAMouseExited

    private void btnAgregarClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarClienteMouseEntered

    }//GEN-LAST:event_btnAgregarClienteMouseEntered

    private void btnAgregarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarClienteMouseExited

    }//GEN-LAST:event_btnAgregarClienteMouseExited

    private void chkFacturar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFacturar2ActionPerformed
        if(!chkFacturar2.isSelected()){
            e3 = false;
            e4 = false;
             btnA1.setEnabled(false);
             btnB1.setEnabled(false);
             txtNombre2.setEnabled(true);
             txtNumero.setEnabled(true);
        }else{

        btnA1.setEnabled(true);
        btnB1.setEnabled(true);
        e3 = true;
        e4 = true;
        chkFacturar.setSelected(false);
        txtNombre2.setText("");
        txtNumero.setText("");
        txtNombre2.setEnabled(false);
        txtNumero.setEnabled(false);
        }
    }//GEN-LAST:event_chkFacturar2ActionPerformed

    private void btnB1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnB1MouseClicked
        if(e3 == true){
        BuscarClientesPV bc = new BuscarClientesPV(null, true);
        bc.setVisible(true);
        if(bc.isAceptado()){
            lblCliente2.setText(bc.getNombreCliente());
            idCliente = bc.getIdCliente();
        }}
    }//GEN-LAST:event_btnB1MouseClicked

    private void btnB1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnB1MouseEntered
        btnBuscar2.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_btnB1MouseEntered

    private void btnB1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnB1MouseExited
        btnBuscar2.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_btnB1MouseExited

    private void btnA1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnA1MouseClicked
        if(e4 == true){
        AgregarClientePV ac = new AgregarClientePV(null, true);
        ac.setVisible(true);
        if(ac.isAceptado()){
            try {
                Cliente c = manejoclientes.buscarClientePorId(ac.getIdCliente());
                lblCliente2.setText(c.getNombre()+" "+c.getaPaterno()+" "+c.getaMaterno());
                idCliente = ac.getIdCliente();
            } catch (SQLException ex) {}
        }}
    }//GEN-LAST:event_btnA1MouseClicked

    private void btnA1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnA1MouseEntered
        btnAgregarCliente2.setBackground(new Color(233,229,229));
    }//GEN-LAST:event_btnA1MouseEntered

    private void btnA1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnA1MouseExited
        btnAgregarCliente2.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnA1MouseExited

    private void btnAgregarCliente2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarCliente2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarCliente2MouseEntered

    private void btnAgregarCliente2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarCliente2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarCliente2MouseExited

    private void txtNombre2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombre2KeyTyped
        char c = evt.getKeyChar();
                if (!Character.isLetter(c)) {
                    evt.consume(); // Ignorar el carácter
                }
    }//GEN-LAST:event_txtNombre2KeyTyped

    private void txtNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroKeyTyped
        char c = evt.getKeyChar();
                if (!Character.isDigit(c)) {
                    evt.consume(); // Ignorar el carácter
                }
    }//GEN-LAST:event_txtNumeroKeyTyped

  private void generarFactura() throws SQLException {
    String uuid = "755AD17E-C125-43CE-B4B7-738AFC3A5FBB";
    String numeroCertificado = "20001000000100005868";
    String fecha;
    String nombreCliente;
    String rfCliente;
    String direccionCliente;
    String ciudadEstadoCp;
    String telefono;
    List<String[]> productos = new ArrayList<>();
    String totalLetra;
    String usoCFDI;
    String tipoPersona = "PERSONA FISICA";
    String subtotal;
    String descuento;
    String impuestos;
    String total;
    
    // Obtener fecha y hora actual
    LocalDate fechaActual = LocalDate.now();
    LocalTime horaActual = LocalTime.now();
    DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("HH:mm:ss");
    fecha = fechaActual.format(dateFormatter) + " " + horaActual.format(timeFormatter);
    
    // Obtener datos del cliente
    Cliente cliFac = manejoclientes.buscarClientePorIdFactura(idCliente);
    nombreCliente = cliFac.getNombre()+" "+cliFac.getaPaterno()+" "+cliFac.getaMaterno();
    rfCliente = cliFac.getRfc();
    direccionCliente = cliFac.getDireccion();
    ciudadEstadoCp = cliFac.getColEstCP();
    telefono = cliFac.getNumero();
    
    // Obtener productos de la venta y calcular subtotal
    List<MostrarProducto> prodFac = manejoproductos.ObtenerProductosPorDetalleVenta(idVenta);
    double subtotalCalculo = 0.0;
    
    for (MostrarProducto producto : prodFac) {
        float cantidad = producto.getCantidadVendida();
        String unidad = producto.getUnidadMedida();
        String descripcion = producto.getDescripcion();
        float costo = producto.getCostoVenta();
        float importe = cantidad * costo;
        
        // Acumular el subtotal (precio sin IVA)
        subtotalCalculo += importe;

        String[] fila = new String[] {
            String.valueOf(cantidad)+"000",
            unidad,
            descripcion,
            String.format("%.2f", costo),
            String.format("%.2f", importe)
        };
        productos.add(fila);
    }

    // Calcular impuestos y totales
    double ivaCalculo = subtotalCalculo * 0.16; // IVA del 16%
    double totalCalculo = subtotalCalculo + ivaCalculo;
    double descuentoCalculo = 0.0;

    // Aplicar descuento si el cliente tiene más de 25 compras
    if (cliFac.getNumeroCompras() > 25) {
        // Ejemplo: 10% de descuento sobre el total
        descuentoCalculo = totalCalculo * 0.10;
        totalCalculo -= descuentoCalculo;
    }

    // Formatear valores para la factura
    subtotal = String.format("%.2f", subtotalCalculo);
    impuestos = String.format("%.2f", ivaCalculo);
    descuento = String.format("%.2f", descuentoCalculo);
    total = String.format("%.2f", totalCalculo);
    totalLetra = NumeroALetras.convertir(totalCalculo);
    
    usoCFDI = manejoventas.obtenerVentaPorId(idVenta).getFormaPago();
    
    // Crear y generar la factura
    DatosFactura df = new DatosFactura(
        uuid, numeroCertificado, fecha, nombreCliente, rfCliente, 
        direccionCliente, ciudadEstadoCp, telefono, productos, 
        totalLetra, usoCFDI, tipoPersona, subtotal, descuento, 
        impuestos, total
    );
    
    GeneradorFacturaPDF gf = new GeneradorFacturaPDF();
    gf.generarFactura(df);
}
    
    
    
    
    public void setListaIDsInventario(JList<Integer> listaIDs) {
    this.lstID = listaIDs;
    this.modeloListaID = (DefaultListModel<Integer>) lstID.getModel();
    }
    
    public void setListaCantidades(JList<String> listaCant) {
    this.lstCant = listaCant;
    this.modeloListaCant = (DefaultListModel<String>) lstCant.getModel();
    }
    

    public void hacerVenta() throws SQLException{
        LocalDate fechaActual = LocalDate.now();
        java.sql.Date fechaBase = java.sql.Date.valueOf(fechaActual);
        Double mt = Double.parseDouble(lblTotal.getText());
        String est = "Completado";
        int idPago;
        
        String eleccion = cboForma.getSelectedItem().toString();
        if(eleccion.equals("Efectivo")){
            idPago = 1;
        }else{
            idPago = 2;
        }
        
        
        if(!chkFacturar.isSelected()){
        
            
        int idCli = manejoclientes.insertarClienteVentaNormalSinRfc("Comúm", "Sin numero");
        int idPag = hacerventa.insertarPago(mt, fechaBase, est, idPago);
        int idVen = hacerventa.insertarVenta(mt, fechaBase, idPag, idCli);
        
        idVenta = idVen;
        System.out.println("id Venta "+idVenta);
        
          for (int i = 0; i < modeloListaID.getSize(); i++) {
        int idProd = modeloListaID.getElementAt(i);
        int idInventario = manejoinventario.obtenerIDInventarioPorIdProducto(idProd);
        Producto prod = manejoproductos.ObtenerProductoPorid(idProd);
              System.out.println("id Inventario: "+idInventario+" y id Producto: "+idProd);
        String valorStr = modeloListaCant.getElementAt(i).replace("-", "").replace(prod.getUnidadMedida(), "").replace("s", "").trim();
        int cantidad = Integer.parseInt(valorStr);
        boolean insertado = hacerventa.insertarDetalleVenta(idInventario, idVen, cantidad);
        System.out.println(idInventario+" "+idVen+" "+cantidad);
        
        }
        
        }else{
            
            if(!lblCliente.getText().equals("-")){
            
             int idPag = hacerventa.insertarPago(mt, fechaBase, est, idPago);
             int idVen = hacerventa.insertarVenta(mt, fechaBase, idPag, idCliente);
             idVenta = idVen;
        System.out.println("id venta: "+idVen);
        
          for (int i = 0; i < modeloListaID.getSize(); i++) {
        int idProd = modeloListaID.getElementAt(i);
        int idInventario = manejoinventario.obtenerIDInventarioPorIdProducto(idProd);
        Producto prod = manejoproductos.ObtenerProductoPorid(idProd);
              System.out.println("id Inventario: "+idInventario+" y id Producto: "+idProd);
        String valorStr = modeloListaCant.getElementAt(i).replace("-", "").replace(prod.getUnidadMedida(), "").replace("s", "").trim();
        int cantidad = Integer.parseInt(valorStr);
        boolean insertado = hacerventa.insertarDetalleVenta(idInventario, idVen, cantidad);
        System.out.println(idInventario+" "+idVen+" "+cantidad);
        
        }}
        }
    }
    
    
    public void hacerVentaBancaria() throws SQLException{
    LocalDate fechaActual = LocalDate.now();
    java.sql.Date fechaBase = java.sql.Date.valueOf(fechaActual);
    Double mt = Double.parseDouble(lblTotal.getText());
    String est = "Pendiente";
    int idPago = 2;
    String nCliente = txtNombre2.getText();
    String num = txtNumero.getText();

    
    // Si la validación pasa, continuar con la lógica de la venta bancaria
    if(!chkFacturar2.isSelected()){
        
        
        // **VALIDACIÓN DE CAMPOS BANCARIOS AL INICIO**
//    if(nCliente.equals("Ingresa un nombre") || nCliente.isEmpty()){
//        JOptionPane.showMessageDialog(null, "No puedes dejar campos vacios, Ingresa un nombre");
//        return; // Detener la ejecución si el nombre está vacío
//    }
//    if(num.equals("Ingresa un numero") || num.isEmpty()){
//        JOptionPane.showMessageDialog(null, "No puedes dejar campos vacios, Ingresa un numero");
//        return; // Detener la ejecución si el número está vacío
//    }

        int idCli = manejoclientes.insertarClienteVentaNormalSinRfc(nCliente, num);
        int idPag = hacerventa.insertarPago(mt, fechaBase, est, idPago);
        int idVen = hacerventa.insertarVenta(mt, fechaBase, idPag, idCli);
        idVenta = idVen;
        System.out.println("id Venta "+idVenta);

        for (int i = 0; i < modeloListaID.getSize(); i++) {
            int idProd = modeloListaID.getElementAt(i);
            int idInventario = manejoinventario.obtenerIDInventarioPorIdProducto(idProd);
            Producto prod = manejoproductos.ObtenerProductoPorid(idProd);
            System.out.println("id Inventario: "+idInventario+" y id Producto: "+idProd);
            String valorStr = modeloListaCant.getElementAt(i).replace("-", "").replace(prod.getUnidadMedida(), "").replace("s", "").trim();
            int cantidad = Integer.parseInt(valorStr);
            boolean insertado = hacerventa.insertarDetalleVenta(idInventario, idVen, cantidad);
            System.out.println(idInventario+" "+idVen+" "+cantidad);
        }
    } else {
        if(!lblCliente2.getText().equals("-")){
            int idPag = hacerventa.insertarPago(mt, fechaBase, est, idPago);
            int idVen = hacerventa.insertarVenta(mt, fechaBase, idPag, idCliente);
            idVenta = idVen;
            System.out.println("id venta: "+idVen);

            for (int i = 0; i < modeloListaID.getSize(); i++) {
                int idProd = modeloListaID.getElementAt(i);
                int idInventario = manejoinventario.obtenerIDInventarioPorIdProducto(idProd);
                Producto prod = manejoproductos.ObtenerProductoPorid(idProd);
                System.out.println("id Inventario: "+idInventario+" y id Producto: "+idProd);
                String valorStr = modeloListaCant.getElementAt(i).replace("-", "").replace(prod.getUnidadMedida(), "").replace("s", "").trim();
                int cantidad = Integer.parseInt(valorStr);
                boolean insertado = hacerventa.insertarDetalleVenta(idInventario, idVen, cantidad);
                System.out.println(idInventario+" "+idVen+" "+cantidad);
            }
        }
    }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PagarVenta dialog = new PagarVenta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnA;
    private javax.swing.JLabel btnA1;
    private javax.swing.JButton btnAceptar;
    private UI.PanelRound btnAgregarCliente;
    private UI.PanelRound btnAgregarCliente2;
    private javax.swing.JLabel btnB;
    private javax.swing.JLabel btnB1;
    private UI.PanelRound btnBuscar;
    private UI.PanelRound btnBuscar2;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cboForma;
    private javax.swing.JCheckBox chkFacturar;
    private javax.swing.JCheckBox chkFacturar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lblCambio;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblCliente2;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotal2;
    private UI.PanelRound panelRound1;
    private UI.PanelRound pnlAceptar;
    private UI.PanelRound pnlBancario;
    private UI.PanelRound pnlCancelar;
    private UI.PanelRound pnlEfectivo;
    private javax.swing.JSpinner sprRecibido;
    private javax.swing.JTextField txtNombre2;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
